# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
I copy the code and tested, and saw that it wouldn't run  `console.log('Outside the loop');`. I think it's because once the `return` is hit in the loop, it terminates the whole 'bailOut` function.

# Teacher Feedback
